---
ike:
  global:
    data_path: /var/ike

ike_pki:
  infos:
    state: "Ile-De-France"
    locality: "Paris"
    country: "FR"
    root_cn: "ILKI Kubernetes Engine"
    expirity: "+3650d"
  management:
    rotate_certificats: False

ike_base_components:
  etcd:
    release: v3.4.14
    update: false
    check: true
    data_path: /var/lib/etcd
  kubernetes:
    release: v1.20.2
    update: false
  container:
    engine: containerd
# release : Only Supported if container engine is set to docker
    release: ""
#    update: false

ike_network:
  cni_plugin: calico
  mtu: 0
  cidr:
    pod: 10.33.0.0/16
    service: 10.32.0.0/24
  service_ip:
    kubernetes: 10.32.0.1 
    coredns: 10.32.0.10
  nodeport:
    range: 30000-32000
  external_loadbalancing:
    enabled: True
    ip_range: 10.10.20.50-10.10.20.250
    secret_key: LGyt2l9XftOxEUIeFf2w0eCM7KjyQdkHform0gldYBKMORWkfQIsfXW0sQlo1VjJBB17shY5RtLg0klDNqNq4PAhNaub+olSka61LxV73KN2VaJY/snrZmHbdf/a7DfdzaeQ5pzP6D5O7zbUZwfb5ASOhNrG8aDMY3rkf4ZzHkc=
  kube_proxy:
    mode: ipvs
    algorithm: rr

ike_features:
  coredns:
    release: "1.8.0"
    replicas: 2
  storage:
    enabled: false
    release: "2.5.0"
    jiva:
      data_path: /var/openebs
      fs_type: ext4
    hostpath:
      data_path: /var/local-hostpath
  dashboard:
    enabled: false
    generate_admin_token: false
  metrics_server:
    enabled: false
    release: v0.4.1
  ingress:
    controller: nginx
    release: v0.43.0
  monitoring:
    enabled: false
    persistent: false
    admin:
      user: administrator
      password: P@ssw0rd

ike_populate_etc_hosts: false

# Security
ike_encrypt_etcd_keys:
# Warrning: If multiple keys are defined ONLY LAST KEY is used for encrypt and decrypt.
# Other keys are used only for decrypt purpose. Keys can be generated with command: head -c 32 /dev/urandom | base64
  key1:
    secret: 1fJcKt6vBxMt+AkBanoaxFF2O6ytHIkETNgQWv4b/+Q=

#restoration_snapshot_file: /path/snopshot/file Located on {{ etcd_data_directory }}
