---
# Stop the Services before uninstalling them
- name: Stop Kubelet Service
  systemd:
    state: stopped
    name: kubelet

- name: Stop Kube-proxy Service
  systemd:
    state: stopped
    name: kube-proxy

# Delete Services Definition
- name: Delete Kubelet Service
  file:
    path: /etc/systemd/system/kubelet.service
    state: absent
  notify:
    - Reload daemons

- name: Delete Kube-proxy Service
  file:
    path: /etc/systemd/system/kube-proxy.service
    state: absent
  notify:
    - Reload daemons

# Delete PKI files and Data Directory
- name: Delete PKI files
  file:
    path: /etc/kubernetes
    state: absent

# Delete Binaries
- name: Delete Node Binaries
  file:
    path: /usr/local/bin/kubernetes
    state: absent

# Delete Logs
- name: Delete Logs
  file:
    path: /var/log/kubernetes
    state: absent
