---
ilke:
  global:
    data_path: /var/ilke

ilke_pki:
  infos:
    state: "Illinois"
    locality: "Sherrard"
    country: "US"
    root_cn: "ILKI Kubernetes Engine"
    expirity: "+3650d"
  management:
    rotate_certificats: True

ilke_base_components:
  etcd:
    release: v3.4.14
    upgrade: False
    check: true
    data_path: /var/lib/etcd
    backup:
      enabled: False
      crontab: "*/30 * * * *"
      storage:
        capacity: 10Gi
        enabled: False
        type: "storageclass"
        storageclass:
          name: "default-jiva"
        persistentvolume:
          name: "my-pv-backup-etcd"
          storageclass: "my-storageclass-name"
        hostpath:
          nodename: "master1"
          path: /var/etcd-backup
  kubernetes:
    release: v1.21.4
    upgrade: false
  container:
    engine: docker
# release : Only Supported if container engine is set to docker
    release: ""
#    upgrade: false

ilke_network:
  cni_plugin: calico
  mtu: 0
  cidr:
    pod: 10.33.0.0/16
    service: 10.32.0.0/16
  service_ip:
    kubernetes: 10.32.0.1 
    coredns: 10.32.0.10
  nodeport:
    range: 30000-32000
  external_loadbalancing:
    enabled: False
    ip_range: 10.10.20.50-10.10.20.250
    secret_key:
  kube_proxy:
    mode: ipvs
    algorithm: rr

ilke_features:
  coredns:
    release: "1.8.3"
    replicas: 2
  reloader:
    enabled: false
    release: "0.0.89"
  storage:
    enabled: false
    release: "2.8.0"
    jiva:
      data_path: /var/openebs
      fs_type: ext4
    hostpath:
      data_path: /var/local-hostpath
  dashboard:
    enabled: false
    generate_admin_token: false
    release: v2.2.0
  metrics_server:
    enabled: false
  ingress:
    controller: ""
    release: v0.46.0
  monitoring:
    enabled: false
    persistent: false
    admin:
      user: administrator
      password: P@ssw0rd
  logrotate:
    enabled: false
    crontab: "* 2 * * *"
    day_retention: 14

ilke_populate_etc_hosts: true

# Security
#ilke_encrypt_etcd_keys:
# Warrning: If multiple keys are defined ONLY LAST KEY is used for encrypt and decrypt.
# Other keys are used only for decrypt purpose. Keys can be generated with command: head -c 32 /dev/urandom | base64
#  key1:
#    secret: 1fJcKt6vBxMt+AkBanoaxFF2O6ytHIkETNgQWv4b/+Q=

#restoration_snapshot_file: /path/snopshot/file Located on {{ etcd_data_directory }}
