---
- name: Delete Jiva
  file:
    path: "{{ ilke_features.storage.jiva.data_path }}"
    state: absent

- name: Delete HostPath
  file:
    path: "{{ ilke_features.storage.hostpath.data_path }}"
    state: absent
