---
# Stop Runtime
- name: Stop Runtime
  systemd:
    state: stopped
    name: containerd
  tags: ['never', 'uninstall']

# Uninstall Containerd
- name: Uninstall Containerd
  package:
    name: containerd.io
    state: absent
  tags: ['never', 'uninstall']

# Delete Config Files and Data Directory
- name: Delete Containerd Config Files and Data Directory
  file:
    path: /etc/containerd
    state: absent
  tags: ['never', 'uninstall']

# Delete Data
- name: Delete Data
  file:
    path: /var/lib/containerd
    state: absent
  tags: ['never', 'uninstall']

# Delete all Container Network Interface (CNI) on the host
- name: Delete all CNI 
  file:
    path: /etc/cni/net.d
    state: absent
  tags: ['never', 'uninstall']
