- name: Create tempdir
  tempfile:
    state: directory
    suffix: backup_etcd
  register: backup_etcd_tempdir
  changed_when: false

- name: Render templates
  template:
    dest: "{{ backup_etcd_tempdir.path }}/backup_etcd.yaml"
    src: "backup-etcd-cronjob.yaml.j2"
  changed_when: false

- name: Apply templates
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf apply -f {{ backup_etcd_tempdir.path }}/backup_etcd.yaml
  register: apply_backup_etcd
  changed_when: >
    apply_backup_etcd.stdout is search("created")
    or apply_backup_etcd.stdout is search("configured")

- name: Cleanup tempdir
  file:
    state: absent
    path: "{{ backup_etcd_tempdir.path }}"
  changed_when: false
